name: Nest.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Check out the repository into your actual app folder
        uses: actions/checkout@v2
        with:
          path: /home/administrator/nest-cicd-implementation/ci-cd-implementation

      - name: Show current folder and contents
        run: |
          cd /home/administrator/nest-cicd-implementation/ci-cd-implementation
          echo "Current Directory:"
          pwd
          echo "Files:"
          ls -alh

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd /home/administrator/nest-cicd-implementation/ci-cd-implementation && npm install

      - name: Build the project
        run: cd /home/administrator/nest-cicd-implementation/ci-cd-implementation && npm run build

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Stop current PM2 process by name
        run: pm2 stop nestjs-app || true

      - name: Start new PM2 process with name
        run: cd /home/administrator/nest-cicd-implementation/ci-cd-implementation && pm2 start dist/main.js --name nestjs-app

      - name: Save PM2 process list
        run: pm2 save
